### ISSUE TITLE
python3.4 oauth_desktop_login results in an error

### ISSUE THREAD

**Issue by mikeazo** [elderamevans/familysearch-python-sdk-opensource#30]
The following code works fine in python 2.7, but not in 3.4:

```python
from familysearch import FamilySearch

fs = FamilySearch('app name', 'api key')
fs.oauth_desktop_login()
# i then enter my info into the browser
```

Unfortunately, in 3.4, I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    fs.oauth_desktop_login()
  File "familysearch/authentication.py", line 71, in oauth_desktop_login
    self.oauth_code_login(qs)
  File "familysearch/authentication.py", line 86, in oauth_code_login
    "Accept": "application/json"}, nojson=True)
  File "familysearch/__init__.py", line 164, in _request
    data = data.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'

```

**Comment by elderamevans** [comment]
Ooh. Two bugs relating to `oauth_desktop_login`. Definitely high-priority, when I'm able to get to it. Hopefully later today...

**Comment by elderamevans** [comment]
Whoops, that last commit was supposed to be #29 and #30, not #28 and #29...
